### ISSUE TITLE
GlobalStyles,theme의 부모 브랜치 만들기(feature/[이슈번호]--styles)

### ISSUE THREAD

**Issue by kimdohoon2** [Codeit-Sprint-Part-2-Team-6/Open-Mind#1]
## 작업 목표 (Task Objective)
- GlobalStyles,theme의 부모 브랜치 만들기

## 상위 브랜치 (Parent Branch)
- origin/develop

## 하위 브랜치 계획 (Sub-branch Plan)
- featue/[이슈번호]--styles/_[이슈번호]--global-styles
- featue/[이슈번호]--styles/_[이슈번호]--theme-styles

## 완료 기준 (Definition of Done)
- (feature/[이슈번호]--styles) 브랜치를 만들고 push하기

## 예상 소요 시간 (Estimated Time)
- 1일

## 작업 흐름 (Workflow)
- git checkout develop
- git pull origin develop
- git checkout -b feature/1--styles 
- git push origin  feature/1--styles

## 추가 설명 (Additional Context)
- develop이랑 `merge`했습니다.
- theme.jsx에 device 코드 추가

**Comment by Donghunn-Lee** [comment]
타이틀에서 "[Branch]" 이 부분을 지우고 어떤 페이지 or 기능을 작업할 건지 명시해주시면 될 것 같습니다!

그리고 브랜치를 만들고 다시 또 그 브랜치에서 작업할 기능을 명시하는 게 비효율적인 것 같아서, 브랜치 생성에 대한 내용이 아니라 생성할 브랜치에서 이뤄질 작업에 대해 설명해주시면 좋을 것 같아요.

또 새롭게 만들 브랜치명은 타이틀이 아니라 상위 -> 생성할 브랜치 -> 하위 브랜치 순으로 명시하는 게 더 나을 듯해서 방금 양식을 조금 수정했습니다. 라벨도 만들어 놓는 것을 깜빡해서 지금 추가로 branch, task, imporvement 라벨을 만들어 두겠습니다.

위 이슈는 여유 있으실 때 살짝 수정해주세요!

아 그리고 다른 분들도 확인하실 수 있게 in Review로 옮겨두겠습니다!

**Comment by kimdohoon2** [comment]
네~알겠습니다! 감사합니다~
