### ISSUE TITLE
feature/_25--question-box/78--split-components

### ISSUE THREAD

**Issue by Jeongbin1** [Codeit-Sprint-Part-2-Team-6/Open-Mind#78]
## 작업 목표 (Task Objective)
- QuestionBox 컴포넌트를 분리하고, 수정 삭제 거절 제대로 동작하지 않는 부분을 수정하겠습니다

## 상위 브랜치 (Parent Branch)
- 작업을 진행할 브랜치의 상위 브랜치:
  - `feature/25--question-box`

## 생성할 브랜치 (New Branch)
- 새롭게 생성할 브랜치
  - `feature/_25--question-box/78--split-components`

## 완료 기준 (Definition of Done)
- 작업에 불편함이 줄어들 정도로 컴포넌트 단위를 구분
- 상태 및 api 요청이 제대로 들어가야 함

## 예상 소요 시간 (Estimated Time)
- 1시간 (+-)

## 작업 흐름 (Workflow)
- 브랜치 생성 및 병합 흐름을 기재하세요.
  - [ ] **Step 1**: `feature/25--question-box` 브랜치에서 `feature/_25--question-box/78--split-components` 브랜치 생성
  - [ ] **Step 2**: `feature/_25--question-box/78--split-components` 브랜치에서 작업 후 `feature/25--question-box` 브랜치로 Pull Request 생성

**Comment by Donghunn-Lee** [comment]
아 토스트 이슈를 먼저 보고 코멘트를 적었었는데 잘 해주고 계셨네요! 👍
