### ISSUE TITLE
feature/_25--question-box/79--ui-input-toast

### ISSUE THREAD

**Issue by Jeongbin1** [Codeit-Sprint-Part-2-Team-6/Open-Mind#79]
## 작업 목표 (Task Objective)
- 답변 입력 창에 입력한 대로 답변 영역에 나타나도록 수정
- 답변 완료 / 수정 완료 / 답변 삭제 / 답변 거절 시 토스트 메시지 띄우기

## 상위 브랜치 (Parent Branch)
- 작업을 진행할 브랜치의 상위 브랜치:
  - `feature/25--question-box`

## 생성할 브랜치 (New Branch)
- 새롭게 생성할 브랜치
  - `feature/_25--question-box/79--ui-input-toast`

## 완료 기준 (Definition of Done)
- 답변 영역에 사용자가 입력한 그대로 텍스트가 표시되어야 함
- 각 작업에 따라 토스트 메시지가 잘 생성되어야 함

## 예상 소요 시간 (Estimated Time)
- 1시간 (+-)

## 작업 흐름 (Workflow)
- 브랜치 생성 및 병합 흐름을 기재하세요.
  - [ ] **Step 1**: `feature/25--question-box` 브랜치에서 `feature/_25--question-box/79--ui-input-toast` 브랜치 생성
  - [ ] **Step 2**: `feature/_25--question-box/79--ui-input-toast` 브랜치에서 작업 후 `feature/25--question-box` 브랜치로 Pull Request 생성

## 추가 설명 (Additional Context)
- 괜찮으시면 Header의 ToastMessage 컴포넌트를 분리해서 text를 전달해주는 식으로 작업하겠습니다

**Comment by Donghunn-Lee** [comment]
토스트 컴포넌트화를 제가 미리 했어야 하는데, 괜찮으시면 작업 해주시면 감사합니다.

**Comment by Jeongbin1** [comment]
@Donghunn-Lee 넵넵 크게 어려운 작업은 아니니 앞선 작업 진행하고 바로 이어서 하겠습니다!
